name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for IngestDataService
      run: docker build IngestDataService --file IngestDataService/Dockerfile --tag ingestdataservice:github
    - name: Build the Docker image for ExposeDataService
      run: docker build ExposeDataService --file ExposeDataService/Dockerfile --tag exposedataservice:github
    - name: Build the Docker image for MachineStreamGateway
      run: docker build MachineStreamGateway --file MachineStreamGateway/Dockerfile --tag machinestreamgateway:github
